### PR TITLE
Added lecturers list through api

### PR DESCRIPTION
**Pull request by MickevichYura**
It's work

### CODE REVIEW

**Comment by IstiN** [comment]
Cool, but it need to be on backend side(like university and list of lecturer). We don't need to target just to grsu, we would like to implement common solution for many universities

**Comment by MickevichYura** [comment]
I will try do it

**Comment by MickevichYura** [comment]
List of lecturer was moved to the backend.
Package gson was moved to new module named gson, which is java library.
Added .gigtignore to module backend

**Comment by IstiN** [comment]
Please change module name to "domain"

**Comment by MickevichYura** [comment]
Done

**Pull request merged**
